### PR TITLE
Add podling maturity evaluation.

### PR DESCRIPTION
**Pull request by mike-jumper**
As [discussed on the mailing list](https://lists.apache.org/thread.html/a5259173a8ef4a1d2bb7be2d99d3cbc2ccf8856130ae6e3fe54e079e@%3Cdev.guacamole.apache.org%3E), completing the [maturity evaluation](http://community.apache.org/apache-way/apache-project-maturity-model.html) is an important step prior to conducting the graduation VOTEs.

This PR contains my first attempt at a draft of said evaluation. I've filled out what I believe to be correct for each of the criteria, and I believe things pass on all counts, but this is in need of PPMC (and mentor) review and comments.

### CODE REVIEW

**Comment by necouchman** [comment]
Not sure if my review counts at all, or if it really needs to be mentors, but this looks fine to me.  I read through it and didn't see any points of disagreement, didn't catch any errors, etc.

**Comment by mike-jumper** [comment]
Your review definitely counts. All Guacamole committers are implicitly PPMC.

**Comment by necouchman** [comment]
> Your review definitely counts. All Guacamole committers are implicitly PPMC.

Okay.  I get the IPMC and PPMC confused sometimes.  Anyway, looks good to me!

**Comment by mike-jumper** [comment]
Anyone else have thoughts/input before I remove the "WIP"?

**Comment by jmuehlner** [comment]
Everything looks good to me!

**Comment by mike-jumper** [comment]
Alright then. "WIP" removed.

**Comment by necouchman** [comment]
So is this ready to merge, and is it something you want me to do?

**Comment by mike-jumper** [comment]
Yes, if you approve the changes, please merge. Once merged, I can kick off the website redeploy.

**Pull request merged**
